// This code currently all generated by ChatGPT

const express = require('express');
const http = require('http');
const WebSocket = require('ws');

const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });

let players = [];

wss.on('connection', (ws) => {
    console.log('A player connected');
    
    ws.on('message', (message) => {
        const data = JSON.parse(message);
        console.log('Received:', data);
        
        // Handle different game actions
        if (data.type === 'join') {
            players.push({ id: data.id, ws });
            broadcast({ type: 'updatePlayers', players: players.map(p => p.id) });
        }
    });

    ws.on('close', () => {
        players = players.filter(player => player.ws !== ws);
        broadcast({ type: 'updatePlayers', players: players.map(p => p.id) });
    });
});

function broadcast(data) {
    wss.clients.forEach(client => {
        if (client.readyState === WebSocket.OPEN) {
            client.send(JSON.stringify(data));
        }
    });
}

server.listen(3000, () => {
    console.log('Server is running on http://localhost:3000');
});
